# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46fd2f5f30442b69cfcb81754262fabf6b63817330129284b25ad3e2a26f05099f7546df8d86092ed0c21116c0f747c80bf9989fa2008f08556643b39630c867

test:
  secret_key_base: 3d0a82676d12e0abfb6e721110c2ca1fff07319f7ad0df226fb3c2c1c9cdbe462853b87a7146270898b982b6c714d75e113ece795e993c0eb245503943bfb23b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
